modLoader="javafml"
loaderVersion="[33,)"
license="All rights reserved"
#issueTrackerURL="" #optional
[[mods]] #mandatory
modId="arsplus" #mandatory
version="$1.16.2-1.0.0" #mandatory
displayName="Hallzmine's Ars Plus" #mandatory
displayURL="https://discord.gg/8tAH8CR/" #optional
#logoFile="examplemod.png" #optional
credits="Mithion & The people who gave me ideas." #optional
authors="Hallzmine" #optional
description='''
An add on for Mithion's Mana and Artifice that adds magical crops and soon new dimensions.
'''
[[dependencies.arsplus]]
modId="forge"
mandatory=true
versionRange="[33,)"
ordering="NONE"
side="BOTH"

[[dependencies.arsplus]]
modId="minecraft"
mandatory=true
versionRange="[1.16.2]"
ordering="NONE"
side="BOTH"

[[dependencies.arsplus]]
modId="mana-and-artifice"
mandatory=true
versionRange="[1.0.6-pre7,)"
ordering="NONE"
side="BOTH"